# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Digital Signature Tests

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  # Purely testing keys that have no access to JP systems etc.
  PUBLIC: "-----BEGIN PUBLIC KEY-----\nMIIBITANBgkqhkiG9w0BAQEFAAOCAQ4AMIIBCQKCAQBxjR6W0YiFNM1Aron4VABA\nTkF/HzWRW3U5JYuaS4WzNxn00WnKsWSVthAlrMbAirkTvJHXkxndM55cJdOECQ7A\nQLZ1qsXPepRw6f7Om/y3OZH9SOjMgAS0mNsd6ANtFoDo2yNqT6oEgKh45UbRExIX\n+3ID3vvKgbKHKjWwW1pCMK/5jPGebhYfw3t0tGJpqZ3IjxMX0WSBO9LYJb9z1vBM\nSjaYXHHcWhwXXcYQJhX8dTs35C35zQ6+G6FV12IpmA5Pa7PC4IzKyEl90hJv3qW0\nJMLHA/P+ejpiA81F7QdzD3uF7akm2VFnnFy9HQibcfcoS0xgFKxQE823R8MnzV0D\nAgMBAAE=\n-----END PUBLIC KEY-----"
  PRIVATE: "-----BEGIN RSA PRIVATE KEY-----\nMIIEoQIBAAKCAQBxjR6W0YiFNM1Aron4VABATkF/HzWRW3U5JYuaS4WzNxn00WnK\nsWSVthAlrMbAirkTvJHXkxndM55cJdOECQ7AQLZ1qsXPepRw6f7Om/y3OZH9SOjM\ngAS0mNsd6ANtFoDo2yNqT6oEgKh45UbRExIX+3ID3vvKgbKHKjWwW1pCMK/5jPGe\nbhYfw3t0tGJpqZ3IjxMX0WSBO9LYJb9z1vBMSjaYXHHcWhwXXcYQJhX8dTs35C35\nzQ6+G6FV12IpmA5Pa7PC4IzKyEl90hJv3qW0JMLHA/P+ejpiA81F7QdzD3uF7akm\n2VFnnFy9HQibcfcoS0xgFKxQE823R8MnzV0DAgMBAAECggEAJSo1GtPVxRN1Inh9\n++MyedmjIkJKvBqdEWkyefvB9NhSDIkGAStyanW+bzZPjvFYhhcv/MjOrFGawTo4\nMnzscQw9K+ILAE90ikhr95+iZS3YlHfqihRUde+Zt/4aMPgulQg0XTVZxkN94KPa\nO8/sGiFYPeAbtToh/o9YJzKfJg5tx/6pxfgicvVL5VSFWCtBPeY5zvT17RyGeG2i\nd8JMIRB5Lw1QjVi4YcxaCeDRvyCyU1JYgzX06NO3aPLxCwT+HpG46QDffkAwt7EH\nlucI03aQGRVFeGGq5vfaLVX3NdEEH11J0d8RDhVWdv8q2kvLfG+8IzU0211z7hgD\n9TCc4QKBgQCuQ7QP0D4JVStUhWrw9yAGTBCbaY9WA70Pu/MGFyAGHn1cNeI9v+eZ\n4SpqHpiVOXFTOUkd65F3ZQXr4JohnnTDlVWXDvqkhkpqILKwfiv6wBQcekLn4db7\n/RjMiRkMSyjvwibHydT1IWH02Rrj4L99VjZnKrzoIsKg2H1d2xDQOQKBgQCmz3Qt\n9x/7F1BXsUr8kwRDkkTyEbaBU0nfVhqtRIByK72AhZVZDZvzAzsF8GuvNl7/piMx\nNy/q59cxHiKpYO+sKtLgyB47ucQh9gJwAQndvd1iG+aceoCwdXNU4xzrbbEyzHju\nsUoerWlBSiyPsduU6OLhyKYtPlsvW60hkVSfGwKBgFOEbRqbEfBFGkQiwRMFTRrX\nf6oMGD8AAa81w44qrRVhrXDw/iHcBDJygHJlgXkbE53wOYOWb5wKFaFrflMYbxuB\nSYjhC+yn06gzTZBal9dQERNo4QHi8bbJIQZ9ujxzFQZ7RTzBFUf6HMlM9585Cm0W\nUXJ2QBz888xElSjTIaa5AoGAc+4b1VI5pLz4NmneLplSTk/aoM3UpB6paZEi6yZ/\nilmB00+DkyeVKZgmLiOAA35rGYtyS+MJ510HPniuKD9ZcrM0acpK0MFzYRLjcMoX\n/EbXFDdF15x/0aNe6zEISUqr6x0WMvV+CMIGM70EKT232M7d14Mmkq0SnGA/e+PQ\nBt8CgYBteSMi5xjL6pff9BSZN6zr8F6pqUUjG210GUYt5+VwIkR8+ESk0s2FYT64\n81Hw+dSkyRe9YZ8foBuMAWgncYHMrjkctWj/jeD2JLIVCICJHenI/Lhryk50Mu0Z\ng2rQz8vJcpxykzjeHO91TnP23NotlbaTRsm/D6ddP4Rr58xlGQ==\n-----END RSA PRIVATE KEY-----"

permissions:
  contents: read

jobs:
  test-python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./digital-signature-creation/python
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest
  test-js:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./digital-signature-creation/js
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./digital-signature-creation/js/yarn.lock"
      - run: yarn install --frozen-lockfile
      - run: yarn test
  test-go:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./digital-signature-creation/go
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.19.0"
      - run: go test
  test-java:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./digital-signature-creation/java
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
